### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Sandaidev** [andymwat/TI-84-CE-DooM#2]
The latest commit is from January, there is no open issues nor pull requests at the moment

Any news on this port?

**Comment by andymwat** [comment]
No, the project isn't alive any more.

I lost the motivation to work on it a while ago. The issue is that it isn't really a port; instead, I tried writing the whole thing from scratch with almost no knowledge on how the original Doom works. For the performance to be anywhere close to acceptable, it'd need a full rewrite, by someone more knowledgeable than me.
